feat: UUI-1476
schibsted/m10s-identity-sdk-android-web pull request #1
Opened 2024-08-09 10:19 UTC by pklawikowski-schibsted

m10s changes
repackage
update environment config
update readme

2024-08-13 14:04 UTC, wojtekk requested changes
Great work. I want to ensure and double check that any change will cause user logout? cc @bogdan-niculescu-sch

2024-08-13 14:04 UTC, wojtekk commented on webflows/src/main/java/com/m10s/identity/webflows/user/User.kt
> +        m10sIdentityUrl("/profile-pages")
`/profile-pages` will be available under new URLs:

- PRE: `https://pre.profile-pages.m10s.io/`
- PRO Sweden: `https://account.schibstedmarketplaces.se/`
- PRO Norway: `https://account.schibstedmarketplaces.no/`
- PRO Finland: `https://account.schibstedmarketplaces.fi/`
- PRO Denmark: `https://account.schibstedmarketplaces.dk/`

2024-08-26 08:57 UTC, bogdan-niculescu-sch commented on webflows/src/main/java/com/m10s/identity/webflows/persistence/SessionStorage.kt
> +        private const val PREFERENCE_FILENAME = "M10S_IDENTITY_TOKENS_SHARED_PREFS"
i think these will lead to user logouts, since those are the files where we [save](https://github.com/schibsted/m10s-identity-sdk-android-web/blob/master/webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt#L147) session info either in encrypted or plain

2024-08-26 09:02 UTC, bogdan-niculescu-sch commented on webflows/src/main/java/com/m10s/identity/webflows/persistence/SessionStorage.kt
> +        private const val PREFERENCE_FILENAME = "M10S_IDENTITY_TOKENS_SHARED_PREFS"
either way, i think due to the package name changes from [here](https://github.com/schibsted/m10s-identity-sdk-android-web/blob/feat/UUI-1476-m10s-changes/webflows/src/main/AndroidManifest.xml#L2) (which are necessary), the prefs files will not be accessible anymore either way regardless of the name-change or not, so maintaining users loggedin state is pretty tricky

2024-08-28 11:34 UTC, pklawikowski-schibsted commented on webflows/src/main/java/com/m10s/identity/webflows/persistence/SessionStorage.kt
> +        private const val PREFERENCE_FILENAME = "M10S_IDENTITY_TOKENS_SHARED_PREFS"
If we keep this preference filename, we will have a collision between media and marketplaces? Do we want to share logged in state between those 2 companies?

2024-08-29 07:59 UTC, pklawikowski-schibsted commented on webflows/src/main/java/com/m10s/identity/webflows/persistence/SessionStorage.kt
> +        private const val PREFERENCE_FILENAME = "M10S_IDENTITY_TOKENS_SHARED_PREFS"
Yes I totally agree, new package = new preferences filename.
If we want to read pref files from another package, we will need same keystore signature, which is somehow a privacy policy issue between 2 companies ;)

@wojtekk 
@bogdan-niculescu-sch

2024-08-29 08:22 UTC, MarcinGie approved these changes

2024-08-29 10:52 UTC, wojtekk commented on webflows/src/main/java/com/m10s/identity/webflows/persistence/SessionStorage.kt
> +        private const val PREFERENCE_FILENAME = "M10S_IDENTITY_TOKENS_SHARED_PREFS"
We discuss this topic with Przemysław. He will do research how to keep users logged in

2024-08-30 11:08 UTC, closed without merging