feature/UI-1570 update tech stack
schibsted/m10s-identity-sdk-android-web pull request #2
Opened 2024-08-09 11:48 UTC by pklawikowski-schibsted

Update grade
Update kotlin
Update libs

2024-08-13 14:11 UTC, wojtekk requested changes
Awesome to see these changes!!!

I've left a few small suggesions

2024-08-13 14:11 UTC, wojtekk commented on README.md
> +# m10s Identity Android SDK
```suggestion
# Schibsted Account Android SDK for Marketplaces
```

2024-08-13 14:11 UTC, wojtekk commented on webflows/src/main/java/com/m10s/identity/webflows/tracking/M10sIdentityTrackingEvent.kt
> +const val PROVIDER_COMPONENT = "m10s-identity"
```suggestion
const val PROVIDER_COMPONENT = "schibsted-account"
```

for now but might be changed later.

2024-08-13 14:11 UTC, wojtekk commented on README.md
> +New implementation of the m10s Identity Android SDK using the web flows via
```suggestion
New implementation of the Schibsted Accoung Android SDK for Martkeplaces using the web flows via
```

2024-08-13 14:11 UTC, wojtekk commented on README.md
> +To implement login with m10s Identity in your app, please first have a look at our
```suggestion
To implement login with Schibsted Account for Marketplaces in your app, please first have a look at our
```

2024-08-29 08:23 UTC, MarcinGie approved these changes

2024-08-30 11:08 UTC, closed without merging